language: python
python:
- '3.6'
sudo: false
cache: pip3
install:
- pip3 install -r requirements.txt
- pip3 install coverage
- pip3 install coveralls
script:
- pytest --cov=user_api
- coverage report
- coverage xml
- coveralls
env:
  global:
  - CC_TEST_REPORTER_ID=946ff7a1ca3ae7f39be343e0c3c1f3ab760ca4a28cbcbfe83541fce3fb85c605
before_script:
- psql -U postgres -f user_api_db.sql

- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
#- ./cc-test-reporter before-build"